include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Disable prefer_const_constructors for test files since List.generate can't be const
    prefer_const_constructors: true
    avoid_print: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # Treat certain lints as warnings instead of errors
    avoid_print: warning
